[package]
name = "scores"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23.2"
tui = "0.18.0"
serial = "0.4.0"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
